cuda: conflict glibc@2.42: and cuda@:13.0, fix libxml2 build dependency (#4911)
- Glibc in version 2.41 added some C23 functions that conflict with headers in cuda prior to version 13.1. This results in errors like
  ```
  /usr/include/bits/mathcalls.h(83): error: exception specification is incompatible with that of previous function "cospi" (declared at line 5554 of <redacted>/spack/var/spack/environments/cuda_rqrt_testing/.spack-env/view/bin/../targets/x86_64-linux/include/crt/math_functions.h)
     extern double cospi (double __x) noexcept (true); extern double __cospi (double __x) noexcept (true);
                                      ^
  
  /usr/include/bits/mathcalls.h(85): error: exception specification is incompatible with that of previous function "sinpi" (declared at line 5442 of <redacted>/spack/var/spack/environments/cuda_rqrt_testing/.spack-env/view/bin/../targets/x86_64-linux/include/crt/math_functions.h)
     extern double sinpi (double __x) noexcept (true); extern double __sinpi (double __x) noexcept (true);
                                      ^
  
  /usr/include/bits/mathcalls.h(206): error: exception specification is incompatible with that of previous function "rsqrt" (declared at line 777 of <redacted>/spack/var/spack/environments/cuda_rqrt_testing/.spack-env/view/bin/../targets/x86_64-linux/include/crt/math_functions.h)
     extern double rsqrt (double __x) noexcept (true); extern double __rsqrt (double __x) noexcept (true);
                                      ^
  
  /usr/include/bits/mathcalls.h(83): error: exception specification is incompatible with that of previous function "cospif" (declared at line 5606 of <redacted>/spack/var/spack/environments/cuda_rqrt_testing/.spack-env/view/bin/../targets/x86_64-linux/include/crt/math_functions.h)
     extern float cospif (float __x) noexcept (true); extern float __cospif (float __x) noexcept (true);
                                     ^
  
  /usr/include/bits/mathcalls.h(85): error: exception specification is incompatible with that of previous function "sinpif" (declared at line 5502 of <redacted>/spack/var/spack/environments/cuda_rqrt_testing/.spack-env/view/bin/../targets/x86_64-linux/include/crt/math_functions.h)
     extern float sinpif (float __x) noexcept (true); extern float __sinpif (float __x) noexcept (true);
                                     ^
  
  /usr/include/bits/mathcalls.h(206): error: exception specification is incompatible with that of previous function "rsqrtf" (declared at line 847 of <redacted>/spack/var/spack/environments/cuda_rqrt_testing/.spack-env/view/bin/../targets/x86_64-linux/include/crt/math_functions.h)
     extern float rsqrtf (float __x) noexcept (true); extern float __rsqrtf (float __x) noexcept (true);
  ```
  To avoid this a conflict maker was added. Initially I had a patch of the cuda headers, but while I only needed `rsqrtf` to get cuda 13.0 to work a small test with 12.4 failed with more functions. Since the patch would need to work for many glibc & cuda versions, I went for the simpler, but less user friendly route.
- The cuda installer needs libxml2.so which was erroneously removed as a dependency in #4563. On many systems libxml2 is just installed so one easily misses this dependency. Contrary to what is stated in the PR one needs to check for the libxml dependency on the extracted installer, not the run script. Running `./cuda_12.0.0_525.60.13_linux.run --noexec --target /tmp/cuda_files` and then `cat /tmp/cuda_files/cuda-installer | grep libxml` shows that this is still a build time dependency (also confirmed on systems without libxml2 instaled).